### ISSUE TITLE
Parsing data with empty values

### ISSUE THREAD

**Issue by joshuaspence** [logstash-plugins/logstash-filter-kv#37]
It seems like the `kv` filter doesn't correctly parse empty values, such as `key=` (rather than `key=value`). I am using Logstash 2.3.4 and version 2.1.0 of `logstash-filter-kv`. Here is an example which best illustrates the problem:

```
echo 'foo= bar=baz' | /opt/logstash/bin/logstash -e 'input { stdin {} } filter { kv { source => "message" } } output { stdout { codec => rubydebug {} } }'
Settings: Default pipeline workers: 2
Pipeline main started
{
       "message" => "foo= bar=baz",
      "@version" => "1",
    "@timestamp" => "2016-08-30T23:56:57.137Z",
          "host" => "ip-10-254-2-234",
           "foo" => "bar=baz"
}
```

In this example, I would've expected `{"foo" => "", "bar" => "baz"}` but instead got `{"foo" => "bar=baz"}`.

**Comment by toddiuszho** [comment]
I've come across this, too. The problem is the way the Regexp is being built. [Line 258 of kv.rb](https://github.com/logstash-plugins/logstash-filter-kv/blob/master/lib/logstash/filters/kv.rb#L258) need a `?` right at the end, making the match of EOLN or the next `@field_split` optional. Definitely works for the case where we're not including brackets.

**Comment by toddiuszho** [comment]
Depends on how we interpret `include_brackets`. If it's relaxed, saying "remove 'em if you got 'em, otherwise don't fret," then adding the `?` works. If it's saying "you MUST have some brackets if you asked for them," then more work is needed.

I believe it's the relaxed way.

**Comment by elvarb** [comment]
A similar issue I ran into but in the other direction

Parsing KV string of

    foo="" bar="zoo"

results in

    foo=""
    bar=zoo

So when the field foo is parsed the value returned is exactly "" while I would prefer it to be blank or null instead of ""

First. The KV filter needs to handle ="" that it is empty

Second. The KV filter needs a new option like 

     empty_keys => true

and possibly 

    empty_default => "empty"

Would be also nice to get a array setting for this as well.

    empty_default => ["key1","key1 is empty", "key2","key2 is empty"]

**Comment by yaauie** [comment]
Version 4.2.0 of this plugin, released today, includes an opt-in `whitespace => "strict"` mode, which enables the parser to capture empty unquoted values in the way the person who opened this PR expects. It does so by not allowing arbitrary extra whitespace on either side of the value splitter.
