### ISSUE TITLE
Incorrect handling of value containing quotes

### ISSUE THREAD

**Issue by joshuaspence** [logstash-plugins/logstash-filter-kv#42]
I am having problems with the `kv` filter parsing a value which contains double quotes. I have been able to reproduce my issue with the following RSpec test:

```
  describe "test quotes" do
    config <<-CONFIG
      filter {
        kv {
          field_split => ", "
          value_split => ": "
        }
      }
    CONFIG

    sample 'referrer: "https://www.google.com.au/search?hl=en&q="foobar" +41 2016 .ch&num=100&start=0"' do
      insist { subject.get("referrer") } == 'https://www.google.com.au/search?hl=en&q="foobar" +41 2016 .ch&num=100&start=0"'
    end
  end
```

Is there a way to fix this via configuration, or is it a bug?

**Comment by jordansissel** [comment]
The kv filter, I think, expects values to have internal quotes escaped. A value like `"some"text"here"` should not be valid.

The way I read your test, I would expect `referrer` to be `https://www.google.com.au/search?hl=en&q=`. I haven't run your test, though. Can you show me the output? What do you get instead of what you expected?

**Comment by joshuaspence** [comment]
Thinking about this more and I now think that the `kv` filter isn't at fault here.
