### ISSUE TITLE
Restore removed settings as drepecated

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-filter-kv#46]
#39 renamed some settings and did not keep the old settings as deprecated. Mistakes happen ;)

We need to do the following:

* Restore the old settings and mark them 'deprecated' with a reference to use the new settings
* Make the old settings still do the same behavior as they had before.

Ship a patch release (v4.0.1?) with this fix.

**Comment by jordansissel** [comment]
I put details in the review: https://github.com/logstash-plugins/logstash-filter-kv/pull/39#pullrequestreview-30094718

**Comment by jsvd** [comment]
Thanks for bringing this to attention, I managed this poorly. Just to make sure, the correct way would have been:

Before a new major release (still in 3.x):
1. add trim_value and trim_key with new behaviour
2. add remove_char_value and remove_char_key that do the same as trim and trimkey
3. trim and trimkey become deprecated
4. during register raise an exception if trim_value+remove_char_value or trimkey+remove_char_key are used at the same time (since they parametrize the same feature)

For 4.x:
1. make trim and trimkey obsolete

**Comment by colinsurprenant** [comment]
I believe this issue can now be closed.
